name: PR Rust Core Benchmarks

on:
  pull_request:
    paths:
      - 'scripts/bench_rust_core.py'
      - 'benchmarks/payloads_json_basic.py'
      - '.github/workflows/pr-rust-core.yml'

jobs:
  rust-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Rust core benchmark skeleton
        env:
          DATASON_RUST: '1'
        run: |
          python scripts/bench_rust_core.py save_string --sizes 10k --shapes flat --repeat 1 --output result.json
      - uses: actions/upload-artifact@v4
        with:
          name: rust-core-results
          path: result.json
